apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-12-06T18:04:19Z"
  generation: 2
  labels:
    app: my-app-js
  name: my-app-js
  namespace: default
  resourceVersion: "12490"
  uid: 08c5eb86-314f-47ea-9f38-525187a46742
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: my-app-js
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-app-js
    spec:
      containers:
      - image: tsaussac/node-app
        imagePullPolicy: Always
        name: node-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 5
  conditions:
  - lastTransitionTime: "2022-12-06T18:04:19Z"
    lastUpdateTime: "2022-12-06T18:05:11Z"
    message: ReplicaSet "my-app-js-7ccfb7cfff" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-12-07T15:53:09Z"
    lastUpdateTime: "2022-12-07T15:53:09Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 5
  replicas: 5
  updatedReplicas: 5
